site_name: Lslightly's Stars
site_url: https://lslightly.github.io/stars
repo_url: https://github.com/Lslightly/stars
theme:
  icon:
    repo: fontawesome/brands/github
    tag:
      Go: fontawesome/brands/golang
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
  - stylesheets/extra.css
plugins:
  - tags
  - glightbox
extra:
  generator: true
  tags:
    Go: Go
nav:
  - Home: index.md
  - Details:
    - details/goref.md
    - details/conbon-pprof2csv.md
